# conda env create -f enviroment.yml
name: img_processing
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python = 3.11.4
  - pandas = 2.0.3
  - geopandas = 0.14.3
  - matplotlib = 3.7.2
  - scikit-image = 0.21.0
  - scikit-learn = 1.4.0
  - opencv = 4.8.0
  - pillow = 10.0.0
  - gdal = 3.7.1
  - rasterio = 1.3.8
  - ipykernel
